name: Build

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'
  workflow_dispatch:

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    strategy:
      matrix:
        board: [nice_nano_v2]
        shield: [minimal_keys_left, minimal_keys_right]
        include:
          - board: nice_nano_v2
            shield: settings_reset
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-modules-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build (${{ matrix.shield }})
        run: west build -s zmk/app -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: ${{ matrix.shield }} Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
        
      - name: Rename artifacts
        run: |
          mkdir artifacts
          if [ -f "build/zephyr/zmk.uf2" ]; then
            cp build/zephyr/zmk.uf2 "artifacts/${{ matrix.shield }}-${{ matrix.board }}-zmk.uf2"
          fi

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: artifacts
