name: Build

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Cache west modules
        uses: actions/cache@v3
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-modules-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: West Build
        uses: docker://zmkfirmware/zmk-build-arm:stable
        with:
          entrypoint: /bin/bash
          args: -c "west init -l config && west update && west zephyr-export && west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=minimal_keys_left -DZMK_CONFIG=/github/workspace/config"

      - name: Minimal Keys Left Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware-left
          path: build/zephyr/zmk.uf2

      - name: West Build Right
        uses: docker://zmkfirmware/zmk-build-arm:stable
        with:
          entrypoint: /bin/bash
          args: -c "west build --pristine -s zmk/app -b nice_nano_v2 -- -DSHIELD=minimal_keys_right -DZMK_CONFIG=/github/workspace/config"

      - name: Minimal Keys Right Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware-right
          path: build/zephyr/zmk.uf2 